apiVersion: batch/v1
kind: Job
metadata:
  name: copy-wordpress-content
  namespace: devops-test
spec:
  template:
    spec:
      ttlSecondsAfterFinished: 60
      restartPolicy: OnFailure
      containers:
        - name: copier
          image: alpine/git
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Clonando conteúdo do Git..."
              git clone --depth=1 https://github.com/oairton/convert.git /tmp/repo
              echo "Copiando para PVC..."
              cp -r /tmp/repo/* /dest/
              echo "Copiado!"
          volumeMounts:
            - name: pvc
              mountPath: /dest
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: data-wineteste-0
