name: Continuous Integration

on:
    push:
        branches:
            - main
    paths-ignore:
      - '**.md'
      - '**.gitignore'

jobs:
    test:
        name: Running unit tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 22.1.0
              uses: actions/setup-node@v4
              with:
                node-version: '22.1.0'

            - name: Install dependencies
              run: npm i

            - name: Run unit tests
              run: npm run test:unit

    build:
      name: Build
      runs-on: ubuntu-latest
      needs: test
      steps:
          - uses: actions/checkout@v4
          - name: Use Node.js 22.1.0
            uses: actions/setup-node@v4
            with:
              node-version: '22.1.0'

          - name: Install dependencies
            run: npm i

          - name: Run build
            run: npm run build